
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  petstore

  Sample SAM Template for petstore

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:


  PetsGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:

      CodeUri: PetsGetFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided
      MemorySize: 512
      FunctionName: PetsGetFunction
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

      Events:
        PetsGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets
            Method: GET



  PetsPostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:

      CodeUri: PetsPostFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided
      MemorySize: 512
      FunctionName: PetsPostFunction
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

      Events:
        PetsPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets
            Method: POST



  PetsPetIdGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:

      CodeUri: PetsPetIdGetFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided
      MemorySize: 512
      FunctionName: PetsPetIdGetFunction
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

      Events:
        PetsPetIdGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets/{petId}
            Method: GET



  PetsPetIdDeleteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:

      CodeUri: PetsPetIdDeleteFunction
      Handler: com.networknt.petstore.handler.App::handleRequest
      Runtime: provided
      MemorySize: 512
      FunctionName: PetsPetIdDeleteFunction
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

      Events:
        PetsPetIdDelete:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/pets/{petId}
            Method: DELETE
