version: "2"
#
# Services
#
services:
  saga-example-customer-service:
    build: ./customer-service
    volumes:
      - ./docker/customer-service/config:/config
    ports:
      - 8081:8081
    networks:
      - localnet

  saga-example-order-service:
    build: ./order-service
    volumes:
      - ./docker/order-service/config:/config
    ports:
      - 8082:8082
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true
