# AccessControlHandler will be the last middleware handler before the proxy on the sidecar or the last
# one before the business handler to handle the fine-grained authorization in the business domain.
# Enable Access Control Handler
enabled: ${accessControl.enabled:true}
