---
openapi: "3.1.0"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
  license:
    name: "MIT"
servers:
- url: "http://petstore.swagger.io/v1"
paths:
  /pets:
    get:
      summary: "List all pets"
      operationId: "listPets"
      tags:
      - "pets"
      security:
      - petstore_auth:
        - "read:pets"
      responses:
        "200":
          description: "An paged array of pets in XML"
components:
  securitySchemes:
    petstore_auth:
      type: "oauth2"
      description: "This API uses OAuth 2 with the client credential grant flow."
      flows:
        clientCredentials:
          tokenUrl: "https://localhost:6882/token"
          scopes:
            write:pets: "modify pets in your account"
            read:pets: "read your pets"
