version: "2"
#
# Services
#
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - http.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  tram-todolist-service:
    build: ./
    volumes:
      - ./docker/config:/config
    ports:
      - 8080:8080
      - 8483:8483
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true
