openapi: 3.0.0
servers:
  - url: 'http://goals.cibc.com'
info:
  version: 1.0.24
  title: DGP  Planning service
  description: >-
    Provide endpoint for DGP planning service; Save, Retrieve, Update Goal,
    planning
  contact:
    name: DGP Scrum Team 2
    email: DL-DGPScrumTeam2@cibc.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /planningunit:
    get:
      description: return a planning unit based on input query parameter.
      operationId: getPlanningUnit
      security:
        - planningunit_auth:
            - 'read:Planunit'
    post:
      description: Add Planning Unit
      operationId: AddPlanningUnit
      security:
        - planningunit_auth:
            - 'read:Planunit'
            - 'write:Planunit'
  '/planningunit/{planningUnitId}':
    get:
      description: return a planning unit based on input path parameter.
      operationId: getPlanningUnitById
      security:
        - planningunit_auth:
            - 'read:Planunit'
  '/planningunit/{planningUnitId}/people/{personId}':
    get:
      description: return a person base on the planning unit and person Id.
      operationId: getPersonDetail
      security:
        - planningunit_auth:
            - 'read:Planunit'
    delete:
      description: return a  deleted Id.
      operationId: DeletePersonById
      security:
        - planningunit_auth:
            - 'read:Planunit'
            - 'write:Planunit'
    put:
      description: >-
        update a person info base on the palnning unitid and person id  from the request and
        return the updated person details.
      operationId: UpdatePersonDetails
      security:
        - planningunit_auth:
            - 'read:Planunit'
            - 'write:Planunit'   
  '/planningunit/{planningUnitId}/people':
    post:
      description: >-
        add a person info base on the palnning unitid  from the request and
        return the new person details.
      operationId: CreatePersonForPlanningUnit
      security:
        - planningunit_auth:
            - 'read:Planunit'
            - 'write:Planunit'              
  /goals:
    get:
      description: return a list of goals base on the client's X-ref Id.
      operationId: RetrieveGoalList
      security:
        - goal_auth:
            - 'read:Goals'
    post:
      description: Add Goal
      operationId: AddGoal
      security:
        - goal_auth:
            - 'read:Goals'
            - 'write:Goals'
  '/goals/{goalId}':
    get:
      description: return a goal base on the goalId.
      operationId: RetrieveGoalDetails
      security:
        - goal_auth:
            - 'read:Goals'
    delete:
      description: return a goalId deleted Id.
      operationId: DeleteGoalById
      security:
        - goal_auth:
            - 'read:Goals'
            - 'write:Goals'
    put:
      description: >-
        update a goal base on the goalId and goal details from the request and
        return the updated goal details.
      operationId: UpdateGoalDetails
      security:
        - goal_auth:
            - 'read:Goals'
            - 'write:Goals'
  /goals/{goalId}/recommendations:
    get:
      description: return a goal base on the goalId.
      operationId: getGoalRecommendations
      security:
        - goal_auth:
            - 'read:Goals'
  /goals/goaltypes:
    get:
      description: return all goaltypes.
      operationId: getGoalTypies
      security:
        - goal_auth:
            - 'read:Goals'
  /goals/progress:
    post:
      description: re calc goal progress.
      operationId: goalProgressRecalc
      security:
        - goal_auth:
            - 'read:Goals'
  /clientregistration:
    post:
      description: check client registration and return clientXrefId.
      operationId: clientRegistration
      security:
        - goal_auth:
            - 'read:Goals'
  /plan:
    get:
      description: return a list of plan base on the client's X-ref Id.
      operationId: RetrievePlans
      security:
        - plan_auth:
            - 'read:Plans'
    post:
      description: Add Plan
      operationId: createPlan
      security:
        - plan_auth:
            - 'read:Plans'
            - 'write:Plans'
  '/plan/{planId}':
    get:
      description: return a plan base on the planId.
      operationId: getPlanById
      security:
        - plan_auth:
            - 'read:Plans'
    delete:
      description: return a planId deleted Id.
      operationId: DeletePlanById
      security:
        - plan_auth:
            - 'read:Plans'
            - 'write:Plans'
    put:
      description: >-
        update a plan base on the planId and plan details from the request and
        return the updated plan details.
      operationId: UpdatePlan
      security:
        - plan_auth:
            - 'read:Plans'
            - 'write:Plans'
components:
  securitySchemes:
    goal_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8080/oauth2/code'
          scopes:
            'read:Goals': read access to goals
            'write:Goals': write access to goals
    plan_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8080/oauth2/code'
          scopes:
            'read:Plans': read access to plans
            'write:Plans': write access to Plans
    planningunit_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8080/oauth2/code'
          scopes:
            'read:Planunit': read access to plans
            'write:Planunit': write access to Plans            