

# Handler middleware chain configuration
---
enabled: true

#------------------------------------------------------------------------------
# Support individual handler chains for each separate endpoint. It allows framework
# handlers like health check, server info to bypass majority of the middleware handlers
# and allows mixing multiple frameworks like OpenAPI and GraphQL in the same instance.
#
# handlers  --  list of handlers to be used across chains in this microservice
#               including the routing handlers for ALL endpoints
#           --  format: fully qualified handler class name@optional:given name
# chains    --  allows forming of [1..N] chains, which could be wholly or
#               used to form handler chains for each endpoint
#               ex.: default chain below, reused partially across multiple endpoints
# paths     --  list all the paths to be used for routing within the microservice
#           ----  path: the URI for the endpoint (ex.: path: '/v1/pets')
#           ----  method: the operation in use (ex.: 'post')
#           ----  exec: handlers to be executed -- this element forms the list and
#                       the order of execution for the handlers
#
# IMPORTANT NOTES:
# - to avoid executing a handler, it has to be removed/commented out in the chain
#   or change the enabled:boolean to false for a middleware handler configuration.
# - all handlers, routing handler included, are to be listed in the execution chain
# - for consistency, give a name to each handler; it is easier to refer to a name
#   vs a fully qualified class name and is more elegant
# - you can list in chains the fully qualified handler class names, and avoid using the
#   handlers element altogether
#------------------------------------------------------------------------------
handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  - com.networknt.swagger.SwaggerHandler@specification
  - com.networknt.security.JwtVerifyHandler@security
  - com.networknt.body.BodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.validator.ValidatorHandler@validator
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.info.ServerInfoGetHandler@info
  # - com.networknt.metrics.prometheus.PrometheusGetHandler@getprometheus
  # Business Handlers
  - com.networknt.petstore.handler.PetPostHandler
  - com.networknt.petstore.handler.PetPutHandler
  - com.networknt.petstore.handler.UserUsernameDeleteHandler
  - com.networknt.petstore.handler.UserUsernamePutHandler
  - com.networknt.petstore.handler.UserUsernameGetHandler
  - com.networknt.petstore.handler.PetFindByStatusGetHandler
  - com.networknt.petstore.handler.UserCreateWithListPostHandler
  - com.networknt.petstore.handler.PetPetIdUploadImagePostHandler
  - com.networknt.petstore.handler.StoreInventoryGetHandler
  - com.networknt.petstore.handler.UserLoginGetHandler
  - com.networknt.petstore.handler.UserPostHandler
  - com.networknt.petstore.handler.UserCreateWithArrayPostHandler
  - com.networknt.petstore.handler.PetFindByTagsGetHandler
  - com.networknt.petstore.handler.StoreOrderPostHandler
  - com.networknt.petstore.handler.UserLogoutGetHandler
  - com.networknt.petstore.handler.PetPetIdPostHandler
  - com.networknt.petstore.handler.PetPetIdDeleteHandler
  - com.networknt.petstore.handler.PetPetIdGetHandler
  - com.networknt.petstore.handler.StoreOrderOrderIdDeleteHandler
  - com.networknt.petstore.handler.StoreOrderOrderIdGetHandler


chains:
  default:
    - exception
    - metrics
    - traceability
    - correlation
    - specification
    - security
    - body
    - audit
    - sanitizer
    - validator

paths:
  - path: '/v2/pet'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.PetPostHandler
  - path: '/v2/pet'
    method: 'PUT'
    exec:
      - default
      - com.networknt.petstore.handler.PetPutHandler
  - path: '/v2/user/{username}'
    method: 'DELETE'
    exec:
      - default
      - com.networknt.petstore.handler.UserUsernameDeleteHandler
  - path: '/v2/user/{username}'
    method: 'PUT'
    exec:
      - default
      - com.networknt.petstore.handler.UserUsernamePutHandler
  - path: '/v2/user/{username}'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.UserUsernameGetHandler
  - path: '/v2/pet/findByStatus'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.PetFindByStatusGetHandler
  - path: '/v2/user/createWithList'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.UserCreateWithListPostHandler
  - path: '/v2/pet/{petId}/uploadImage'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.PetPetIdUploadImagePostHandler
  - path: '/v2/store/inventory'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.StoreInventoryGetHandler
  - path: '/v2/user/login'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.UserLoginGetHandler
  - path: '/v2/user'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.UserPostHandler
  - path: '/v2/user/createWithArray'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.UserCreateWithArrayPostHandler
  - path: '/v2/pet/findByTags'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.PetFindByTagsGetHandler
  - path: '/v2/store/order'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.StoreOrderPostHandler
  - path: '/v2/user/logout'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.UserLogoutGetHandler
  - path: '/v2/pet/{petId}'
    method: 'POST'
    exec:
      - default
      - com.networknt.petstore.handler.PetPetIdPostHandler
  - path: '/v2/pet/{petId}'
    method: 'DELETE'
    exec:
      - default
      - com.networknt.petstore.handler.PetPetIdDeleteHandler
  - path: '/v2/pet/{petId}'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.PetPetIdGetHandler
  - path: '/v2/store/order/{orderId}'
    method: 'DELETE'
    exec:
      - default
      - com.networknt.petstore.handler.StoreOrderOrderIdDeleteHandler
  - path: '/v2/store/order/{orderId}'
    method: 'GET'
    exec:
      - default
      - com.networknt.petstore.handler.StoreOrderOrderIdGetHandler

  - path: '/health/com.networknt.petstore-2.0.0'
    method: 'get'
    exec:
      - health

  - path: '/server/info'
    method: 'get'
    exec:
      - info
