
#change the image tag before you deploy, if using minikube, please use any tag other than "latest"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-binary-deployment
  labels:
    app: backend-binary
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-binary
  template:
    metadata:
      labels:
        app: backend-binary
    spec:
      containers:
        - name: backend-binary
          image: networknt/com.networknt.backend-binary-1.0.0:1.0.0
          ports:
            - containerPort: 8443
          resources:
            requests:
              memory: "64Mi"
              #0.25 cpu
              cpu: "250m"
            limits:
              #0.5 cpu
              memory: "128Mi"
              cpu: "500m"
          #cannot use httpcheck due to the server can be https
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend-binary-service
  labels:
    app: backend-binary
spec:
  selector:
    app: backend-binary
  type: NodePort
  ports:
    - protocol: TCP
      port: 8443