---
description: Cors Http Handler
# If cors handler is enabled or not
enabled: true
# Allowed origins, you can have multiple and with port if port is not 80 or 443
# Wildcard is not supported for security reasons.
allowedOrigins:
- http://localhost
# Support for react dev server.
- http://localhost:3000
# Allowed methods list.
allowedMethods:
- GET
- POST
- OPTIONS
