# This is specific OpenAPI validator configuration file. It is introduced to support multiple
# frameworks in the same server instance and it is recommended. If this file cannot be found,
# the generic validator.yml will be loaded as a fallback.
---
# Enable request validation. Response validation is not done on the server but client.
enabled: ${openapi-validator.enabled:true}
# Log error message if validation error occurs
logError: ${openapi-validator.logError:true}
# Skip body validation set to true if used in light-router, light-proxy and light-spring-boot.
skipBodyValidation: ${openapi-validator.skipBodyValidation:false}
# Enable response validation.
validateResponse: ${openapi-validator.validateResponse:false}
# When a field is set as nullable in the OpenAPI specification, the schema validator validates that it is nullable
# however continues with validation against the nullable field

# If handleNullableField is set to true && incoming field is nullable && value is field: null --> succeed
# If handleNullableField is set to false && incoming field is nullable && value is field: null --> it is up to the type
# validator using the SchemaValidator to handle it.
handleNullableField: ${openapi-validator.handleNullableField:true}
