
#change the image tag before you deploy, if using minikube, please use any tag other than "latest"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isoxml-deployment
  labels:
    app: isoxml
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isoxml
  template:
    metadata:
      labels:
        app: isoxml
    spec:
      containers:
        - name: isoxml
          image: networknt/com.networknt.isoxml-3.1.0:3.1.0
          ports:
            - containerPort: 9443
          resources:
            requests:
              memory: "64Mi"
              #0.25 cpu
              cpu: "250m"
            limits:
              #0.5 cpu
              memory: "128Mi"
              cpu: "500m"
          #cannot use httpcheck due to the server can be https
          readinessProbe:
            tcpSocket:
              port: 9443
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 9443
            initialDelaySeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: isoxml-service
  labels:
    app: isoxml
spec:
  selector:
    app: isoxml
  type: NodePort
  ports:
    - protocol: TCP
      port: 9443
