
#change the image tag before you deploy, if using minikube, please use any tag other than "latest"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: computerstore-service-api-deployment
  labels:
    app: computerstore-service-api
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computerstore-service-api
  template:
    metadata:
      labels:
        app: computerstore-service-api
    spec:
      containers:
        - name: computerstore-service-api
          image: networknt/com.networknt.computerstore-service-api-3.0.1:3.0.1
          ports:
            - containerPort: 8445
          resources:
            requests:
              memory: "64Mi"
              #0.25 cpu
              cpu: "250m"
            limits:
              #0.5 cpu
              memory: "128Mi"
              cpu: "500m"
          #cannot use httpcheck due to the server can be https
          readinessProbe:
            tcpSocket:
              port: 8445
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8445
            initialDelaySeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: computerstore-service-api-service
  labels:
    app: computerstore-service-api
spec:
  selector:
    app: computerstore-service-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8445
