# This is the config file to replace the default config loader to a customized one.
# For example, load the config files from the config server instead of filesystem.
# The following dummy entry is just to prevent the warning message during startup.
# For real config loader config, please follow the format below with your implementation.
configLoaderClass: com.networknt.server.DefaultConfigLoader
projectName: light-example
projectVersion: 1.0.0
serviceName: com.networknt.petstore-1.0.0
serviceVersion: 1.0.1

